<?php 
define('SCC_IMAGESSLIDER_MODULE_DIR', _PS_MODULE_DIR_ . 'psmodimageslider/');
define('SCC_IMAGESSLIDER_MODULE_IMAGE_DIR', SCC_IMAGESSLIDER_MODULE_DIR.'images/');

define('SCC_IMAGESSLIDER_MODULE_URL', 'modules/psmodimageslider/');
define('SCC_IMAGESSLIDER_IMAGE_URL', SCC_IMAGESSLIDER_MODULE_URL . 'images/');