<?php 
define('TD_HOME_ADVERTISING_MODULE_DIR', _PS_MODULE_DIR_ . 'tdhomeadvertising/');
define('TD_HOME_ADVERTISING_MODULE_IMAGE_DIR', TD_HOME_ADVERTISING_MODULE_DIR.'images/');

define('TD_HOME_ADVERTISING_MODULE_URL', 'modules/tdhomeadvertising/');
define('TD_HOME_ADVERTISING_IMAGE_URL', TD_HOME_ADVERTISING_MODULE_URL . 'images/');